name: Build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: thalesmg
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: build
        run: nix build .
      - name: copy dist
        run: "mkdir ./dist && cp -R result/* ./dist/"
      - name: deploy netlify
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          publish-dir: ./dist/
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ github.event.head_commit.message }}
          enable-commit-comment: true
          enable-pull-request-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: deploy gh pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          target_branch: gh-pages
          build_dir: ./dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
